version: '3'
services:
  app:
    image: docker.pkg.github.com/artman-training-projects/purpleschool-nextjs/top-app-demo:develop
    container_name: top-app-demo
    restart: always
    ports:
      - 3000:3000
